### ISSUE TITLE
Routing on current website negatively impacts other services running on the server.

### ISSUE THREAD

**Issue by phntxx** [hackaburg/website#90]
With the current way the routing is set up, this website container blocks all other services operating under the same domain (not subdomain), but with differing subpaths.

# Steps to reproduce:

This can be reproduced using this `docker-compose.yml`:

```yaml
services
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  website:
    image: hackaburg/website:latest
    labels:
      traefik.enable: true
      traefik.http.services.websitehb.loadbalancer.server.port: 8080
      traefik.http.routers.websitehb.service: websitehb
      traefik.http.routers.websitehb.rule: Host(`hackaburg.de`)

  website18:
    image: hackaburg/website:hb-2018
    labels:
      traefik.enable: true
      traefik.http.services.websitehb18.loadbalancer.server.port: 8080
      traefik.http.routers.websitehb18.service: websitehb18
      traefik.http.routers.websitehb18.rule: HostRegexp(`^hackaburg\\.(org|de)`) && PathPrefix(`/2018/`)
      traefik.http.routers.websitehb18.middlewares: websitehb18
      traefik.http.middlewares.websitehb18.stripprefix.prefixes: /2018
```

## Expected behavior:

A `GET` request to `https://hackaburg.de/2018` gets internally redirected by traefik and the container `website18` returns a response.

## Actual behavior:

The current version of the website (`website` container) interprets said `GET` request as a request that it must fulfill, yet cannot find the subpath `/2018` within itself and thus throws a 404 error.
